### ISSUE TITLE
[intermittent] 500 Internal Server Error seen during uds deploy

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-mas#96]
Creating issue to track this problem that was seen in a pipeline run to track how frequently we see it

![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/29608224/1d59a3ac-796a-47c9-967c-10918e990b32)

**Comment by NatarajBTI** [comment]
@ocofaigh - Can we close this issue? as the MAS DA deployment is stable now and if we start using Openshift 4.14, these intermittent issue shouldn't be seen as IKS team as mentioned 4.14 and later uses Konnectivity & update window of master is less because of that. I am okay if we have to test it with 4.14 version for some runs and then close this issue based on the result of those runs.
If that's the case then can we defer this issue? Thanks

**Comment by ocofaigh** [comment]
Agree - issue was related to the health of the cluster. Since the docs will specify the cluster must be healthy before deploying, I'm going to close this
